name: Build, Test, Package, and Deploy #test

on:
  push:
    branches:
      - main

env:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          maven-version: '3.8.5'

      - name: Build project
        run: mvn compile

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          maven-version: '3.8.5'

      - name: Run tests
        run: mvn test

  package:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          maven-version: '3.8.5'

      - name: Package application
        run: mvn package

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: game2048
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker image
        run: echo -e 'FROM tomcat:9-jdk17-openjdk-slim \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .

      - name: Run Docker container
        run: docker run --rm -d --name tomcat -p 8080:8080 game2048

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to be ready..."
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080/game2048); do
            printf '.'
            sleep 1
          done
          echo "Deployment is ready!"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: target
