name: Exercise 1.c
on: [push]

jobs:
  build:
    runs-on: self-hosted

    container:
      image: maven:3.8.5-openjdk-17

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn compile

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_number }}
          path: target